.eslintrc.json, .husky/pre-commit, app/models/tmdb.server.ts, app/models/tmdb.types.ts, app/routes/index.tsx, app/routes/trending.tsx, app/src/components/Media/MediaItem.tsx, app/src/components/Media/MediaList.tsx, package.json, yarn.lock
@Khanhtran47 
Định đợi m làm xong cái header gì đó rồi commit lên, đều chắc t nớ lên luôn.
Chỉ là copy code cũ qua thôi, không có gì mới cả.
update: https://react-movie-git-feature-18-khanhtran47.vercel.app/trending
=> Feature/#18: Trending page

app/entry.server.tsx, app/routes/about.tsx, app/routes/anime.tsx, app/routes/index.tsx, app/routes/list-animes.tsx, app/routes/list-movies.tsx, app/routes/list-tv-shows.tsx, app/routes/movie.tsx, app/routes/tv-show.tsx, app/src/components/AppBar.tsx, app/src/components/DrawerHeader.tsx, app/src/components/Header.tsx, app/src/components/LeftDrawer.tsx, app/styles/app.css, package.json, yarn.lock
nó vẫn còn lỗi ni đều style vẫn chạy đc đều t thấy nó render lại khi chuyển page k bt có phải do lỗi ni k
lỗi ở hàm replace ni nó hình như thay cái head, t chưa sửa đc nên đang để rứa, có thể chuyển replace thành concat hoặc chuyển cái style ni sang document bên root luôn
=> feature/#5: header

app/models/tmdb.server.ts, app/models/tmdb.types.ts, app/routes/api/trending.tsx, app/routes/imdb-top.tsx, app/routes/movies/$id.tsx, app/routes/movies/index.tsx, app/routes/new-releases.tsx, app/routes/recommendations.tsx, app/routes/trending.tsx, app/routes/tv-shows/$id.tsx, app/routes/tv-shows/index.tsx, app/routes/watch-history.tsx, app/src/components/Media/MediaList.tsx
- api routes: allow client-side rendering without exposing secret keys
- pages: more pages (basic pages) that match all clickable links on the current app
=> feature(routing): #20

app/routes/search/movie/$movieKeyword.tsx, app/routes/search/movie/index.tsx, app/routes/search/people/$peopleKeyword.tsx, app/routes/search/people/index.tsx, app/routes/search/tv/$tvKeyword.tsx, app/routes/search/tv/index.tsx, app/src/components/filter/Filter.tsx
=> feat: search on enter press (#102)

app/src/components/filter/Filter.tsx
=> fix: useNavigate instead of Link on LetGo button

app/root.tsx, app/routes/index.tsx, app/routes/movies/$movieId.watch.tsx, app/routes/tv-shows/$tvId.watch.tsx, app/src/components/Media/MediaDetail.tsx, app/src/components/Media/MediaItem.tsx, app/src/components/Media/MediaList.tsx, app/src/components/elements/NavLink.tsx, app/src/components/layouts/Header.tsx, app/src/components/layouts/LeftDrawer.tsx, app/src/components/people/PeopleItem.tsx, app/src/components/people/PeopleList.tsx
@ctuanle 
Move text outside image: show tooltip on hovering text (for better performance for swiperJs)
New design for people image: zoom on hovering image
=> bugfix/#127: re-design for MediaItem and PeopleItem

app/routes/movies/discover.tsx, app/routes/tv-shows/discover.tsx, app/src/components/media/MediaList.tsx
- using localStorage
- only on discover pages for now (show list type selector)
=> feat: persist selected list type

app/routes/api/youtube-video.ts, app/routes/index.tsx, app/routes/movies/$movieId.tsx, app/routes/movies/$movieId/videos.tsx, app/routes/tv-shows/$tvId.tsx, app/routes/tv-shows/$tvId/videos.tsx, app/services/youtube/utils.server.ts, app/services/youtube/youtube.server.ts, app/services/youtube/youtube.types.ts, app/src/components/elements/Tab.tsx, app/src/components/elements/modal/WatchTrailerModal.tsx, app/src/components/media/MediaDetail.tsx, app/src/components/media/item/CardItem.tsx
@ctuanle add video tab in detail page
- add watch trailer button
- add video tab
- add new component: WatchTrailerModal
- add new API: youtube api: https://developers.google.com/youtube/v3/docs/videos/list
=> ✨ feat: add video tab in detail page (#104)

app/src/components/layouts/Header.tsx
- chỗ này t k để searchParams vô vì kiểu nếu mới đổi lang xong đổi thêm lần nữa là dễ ra như /?lng=en&lng=fr blabla thì nó k chính xác
=> fix: change target url after changing language

app/root.tsx, app/routes/movies/$movieId/photos.tsx, app/routes/people/$peopleId/media.tsx, app/routes/tv-shows/$tvId/photos.tsx, app/src/components/elements/NavLink.tsx, app/src/components/elements/Tab.tsx, app/src/components/layouts/BottomNav.tsx, app/src/components/layouts/Header.tsx, app/src/components/layouts/LeftDrawer.tsx, app/src/components/media/item/BannerItem.tsx, app/src/components/media/item/CardItem.tsx, public/site.webmanifest
@ctuanle add 6 new color themes: 
bumblebee: 
synthwave: 
retro:
dracula:
autumn:
night:
some tools and docs used in this PR:
[daisyUI theme](https://daisyui.com/docs/themes/)
[daisyUI theme info](https://github.com/saadeghi/daisyui/blob/master/src/colors/themes.js)
[Eva Design System](https://colors.eva.design/)
[nextUi theme info](https://github.com/nextui-org/nextui/blob/main/packages/react/src/theme/dark-theme.ts)
=> :sparkles: feat: add color theme (#5)

app/routes/index.tsx, app/src/assets/icons/VolumeOffIcon.js, app/src/assets/icons/VolumeUpIcon.js, app/src/components/layouts/Header.tsx, app/src/components/media/MediaList.tsx, app/src/components/media/item/BannerItem.tsx, app/src/components/media/item/CardItem.tsx, app/src/components/media/item/CardItemHover.tsx, app/src/components/media/item/index.tsx, app/src/components/media/list/MediaListBanner.tsx, package.json
@ctuanle
- add playing trailer in CardItemHover
- fix movie trailer load multi-times in BannerItem
- add mute button for muting or unmuting audio in BannerItem, CardItemHover
- pause trailer when out of view or visibility change in BannerItem
=> feat: add playing trailer in CardItemHover

app/routes/anime.tsx, app/routes/anime/index.tsx, app/routes/anime/popular.tsx, app/routes/anime/trending.tsx, app/src/components/anime/AnimeList.tsx, app/src/components/anime/item/AnimeCardItem.tsx, app/src/components/anime/list/AnimeListGrid.tsx, app/src/components/anime/list/index.tsx, app/src/components/layouts/Header.tsx, app/src/components/media/item/CardItem.tsx, app/src/components/media/list/MediaListGrid.tsx
@ctuanle add custom virtual list and infinite scrolling
=> feat: add anime routes: popular and trending

app/hooks/useEventCallback.ts, app/hooks/useEventListener.ts, app/hooks/useIsomorphicLayoutEffect.ts, app/hooks/useLocalStorage.ts, app/services/consumet/anilist/utils.server.ts, app/src/assets/icons/ChevronLeftIcon.js, app/src/assets/icons/ChevronRightIcon.js, app/src/assets/icons/PlayIcon.js, app/src/assets/icons/StopIcon.js, app/src/components/anime/AnimeList.tsx, app/src/components/anime/item/AnimeBannerItemDesktop.tsx, app/src/components/anime/item/AnimeCardItem.tsx, app/src/components/anime/item/AnimeCardItemHover.tsx, app/src/components/anime/list/AnimeListBanner.tsx, app/src/components/media/MediaList.tsx, app/src/components/media/item/BannerItemDesktop.tsx, app/src/components/media/item/CardItem.tsx, app/src/components/media/item/CardItemHover.tsx, app/src/components/media/list/MediaListBanner.tsx, app/src/components/people/PeopleList.tsx, app/src/components/styles/svg.ts
@ctuanle 
- add new play trailer button to toggle play trailer in BannerItem and CardItem (default is false for performance)
- add new hooks: useLocalStorage, useEventCallback, useEventListener, useIsomorphicLayoutEffect
- add new icons: PlayIcon, StopIcon
- change icons: ChevronRight, ChevronLeft
- fix some designs in BannerItem and CardItem
- change base url of consumet api
=> feat: :sparkles: add play trailer option

app/routes/movies/$movieId/cast.tsx, app/routes/movies/$movieId/crew.tsx, app/routes/movies/$movieId/index.tsx, app/routes/tv-shows/$tvId/cast.tsx, app/routes/tv-shows/$tvId/crew.tsx, app/routes/tv-shows/$tvId/index.tsx, app/services/tmdb/tmdb.types.ts, app/src/components/people/PeopleItem.tsx
@ctuanle add some info for PeopleItem
=> bug: :bug: fix and add some infos in PeopleItem

app/routes/anime/$animeId.episode.$episodeId.tsx, app/routes/anime/$animeId/episodes.tsx, app/routes/anime/$animeId/overview.tsx, app/routes/api/provider.ts, app/routes/movies/$movieId.tsx, app/routes/movies/$movieId.watch.tsx, app/routes/tv-shows/$tvId.season.$seasonId.episode.$episodeId.tsx, app/routes/tv-shows/$tvId.season.$seasonId/index.tsx, app/routes/tv-shows/$tvId.tsx, app/services/consumet/anilist/anilist.types.ts, app/services/consumet/flixhq/flixhq.types.ts, app/services/loklok/loklok.type.ts, app/services/loklok/movie.server.ts, app/services/loklok/tv.server.ts, app/services/tmdb/tmdb.types.ts, app/src/components/anime/AnimeDetail.tsx, app/src/components/elements/modal/SelectProviderModal.tsx, app/src/components/media/MediaDetail.tsx
@ctuanle add selecting providers for movies, tv series and anime
=> feat: :sparkles: add selecting providers

app/routes/anime/$animeId.tsx, app/routes/api/provider.ts, app/routes/movies/$movieId.tsx, app/routes/tv-shows/$tvId.tsx, app/services/loklok/tv.server.ts, app/src/assets/icons/PhotoIcon.js, app/src/components/anime/AnimeDetail.tsx, app/src/components/anime/item/AnimeBannerItemDesktop.tsx, app/src/components/elements/modal/WatchTrailerModal.tsx, app/src/components/media/item/BannerItemDesktop.tsx
@ctuanle 
- add animation for BannerItem
- save time watch from trailer when navigate detail route
- fix wrong id from loklok for anime route
=> feat: :sparkles: add animation for BannerItem

app/hooks/useSplitArrayIntoPage.ts, app/routes/anime/$animeId.episode.$episodeId.tsx, app/routes/anime/$animeId/episodes.tsx, app/routes/tv-shows/$tvId.season.$seasonId/index.tsx, app/services/consumet/anilist/anilist.server.ts, app/services/consumet/anilist/utils.server.ts, app/src/components/anime/AnimeDetail.tsx, app/src/constants/episodeType.ts
- split fetch data and episodes api separately
- episodes list with number type and split episodes into page (new hook)
=> fix: display episodes in anime route

.env-example, app/routes/__auth/sign-in.tsx, app/routes/__auth/sign-up.tsx, app/routes/anime/$animeId.episode.$episodeId.tsx, app/routes/movies/$movieId.watch.tsx, app/routes/tv-shows/$tvId.season.$seasonId.episode.$episodeId.tsx, app/services/configs.server.ts, app/services/loklok/utils.server.ts, app/services/lru-cache.ts, app/src/components/AuthForm.tsx, app/src/components/elements/filter/Filter.tsx, app/utils/encode.ts, public/locales/en/auth.json, public/locales/fr/auth.json, public/locales/vi/auth.json
=> feat: invited-only sign-up mode

app/routes/watch-history.tsx, app/services/supabase/table.server.ts, app/src/components/media/item/HistoryItem.tsx
- style history item (not so good but better)
- filter by media type
- filter from date to date
=> feat: filter watch history

app/root.tsx, app/routes/anime/$animeId.episode.$episodeId.tsx, app/routes/anime/$animeId/episodes.tsx, app/routes/movies/$movieId.watch.tsx, app/routes/tv-shows/$tvId.season.$seasonId.episode.$episodeId.tsx, app/routes/tv-shows/$tvId.season.$seasonId/index.tsx, app/services/consumet/anilist/anilist.server.ts, app/services/consumet/anilist/anilist.types.ts, app/src/components/elements/player/ArtPlayer.tsx, app/src/components/elements/shared/ListEpisodes.tsx, app/src/components/elements/shared/WatchDetail.tsx, app/src/components/people/PeopleList.tsx, app/src/constants/episodeTypes.ts, package.json, yarn.lock
@ctuanle 
- add detail, list episodes and recommendations in watch route
- player: add next episode button and autoplay option for playing next episode after video ended
- refactor components 
- fix play recent episodes
=> feat: :sparkles: add detail, list episodes and recommendations in watch route

app/hooks/useMediaQuery.ts, app/root.tsx, app/routes/anime/$animeId.tsx, app/routes/people/$peopleId.tsx, app/src/components/layouts/Copyright.tsx
=> feat: :sparkles: add theme color meta tag 

app/routes/anime/$animeId.episode.$episodeId.tsx, app/routes/movies/$movieId.watch.tsx, app/routes/tv-shows/$tvId.season.$seasonId.episode.$episodeId.tsx, app/src/components/elements/modal/SelectProviderModal.tsx, app/src/components/elements/player/ArtPlayer.tsx
@ctuanle just provide subtitle type and it's work 😅
=> fix: :bug: subtitles not showing on mobiles

app/routes/anime/$animeId.episode.$episodeId.tsx, app/routes/anime/$animeId/overview.tsx, app/routes/collections/$collectionsId.tsx, app/routes/movies/$movieId.watch.tsx, app/routes/tv-shows/$tvId.season.$seasonId.episode.$episodeId.tsx, app/routes/tv-shows/$tvId/index.tsx, app/src/components/elements/player/ArtPlayer.tsx, app/src/components/elements/shared/ListEpisodes.tsx, package.json, yarn.lock
@ctuanle 
- fix duplicate subtitles after changing episode
- style: rounded the corner of images in Card
- fix dash player
=> fix: :bug: duplicate subtitles after changing episode

app/routes/anime/$animeId.episode.$episodeId.watch.tsx, app/services/aniskip/aniskip.server.ts, app/src/components/layouts/GlobalPlayer.tsx, app/store/player/usePlayerState.ts
@ctuanle 
add aniskip api for skipping anime opening, ending
=> feat: :sparkles: add aniskip for skipping anime op, ed

app/entry.client.tsx, app/entry.server.tsx, app/root.tsx, app/routes/anime/$animeId.episode.$episodeId.watch.tsx, app/routes/anime/$animeId.tsx, app/routes/anime/index.tsx, app/routes/movies/index.tsx, app/routes/settings.tsx, app/routes/test/design-system.tsx, app/routes/tv-shows/index.tsx, app/src/assets/icons/RefreshIcon.js, app/src/components/CatchBoundaryView.tsx, app/src/components/ErrorBoundaryView.tsx, app/src/components/elements/modal/SearchSubtitle.tsx, app/src/components/elements/modal/SelectProviderModal.tsx, app/src/components/elements/modal/WatchTrailerModal.tsx, app/src/components/layouts/GlobalPlayer.tsx, app/src/components/layouts/Header.tsx, app/src/components/layouts/LeftDrawer.tsx, app/src/components/media/item/BannerItemDesktop.tsx, app/src/components/media/item/CardItem.tsx, app/src/components/media/list/MediaListBanner.tsx, app/src/components/media/list/MediaListGrid.tsx, app/styles/client.context.ts, package.json, yarn.lock
@ctuanle 
- fix: style tags disappear from head during error/catch boundary
- chore: add return home and reload page option for root error/catch boundary
- chore: add disabled tooltip for mobile
- fix: navigate wrong url for select provider modal
=> fix: Style tags disappear from Head during Error/Catch Boundary

app/components/elements/Kbd.tsx, app/components/elements/player/PlayerHotkey.ts, app/components/layouts/GlobalPlayer.tsx, app/routes/settings.tsx, public/locales/en/settings.json, public/locales/fr/settings.json, public/locales/vi/settings.json
@ctuanle 
- add more shortcut keys for player
- add Kbd components for display keyboards
- add Keyboard shortcuts section for player settings page
- fix theme style for info, context menu in the player
=> feat(player): add more shortcut keys

app/components/media/item/BannerItemCompact.tsx, app/components/media/item/BannerItemMobile.tsx, app/components/media/list/MediaListBanner.tsx, app/root.tsx, package.json, yarn.lock
@ctuanle 
- add autoplay for media list banner
- remove fetching logo in banner item for mobiles
- update swiper v9
=> feat: add autoplay for banner list

app/components/media/AnimeDetail.tsx, app/components/media/MediaDetail.tsx, app/routes/collections/$collectionsId.tsx, app/routes/movies/$movieId/cast.tsx, app/routes/movies/$movieId/crew.tsx, app/routes/movies/$movieId/recommendations.tsx, app/routes/movies/$movieId/similar.tsx, app/routes/tv-shows/$tvId.season.$seasonId/cast.tsx, app/routes/tv-shows/$tvId.season.$seasonId/crew.tsx, app/routes/tv-shows/$tvId/cast.tsx, app/routes/tv-shows/$tvId/crew.tsx, app/routes/tv-shows/$tvId/recommendations.tsx, app/routes/tv-shows/$tvId/similar.tsx
=> fix: update scroll into view when changing pages

app/constants/tabLinks.ts, app/routes/tv-shows/$tvId.season.$seasonId.tsx
[demo](https://sora-git-feature-tv-season-detail-khanhtran47.vercel.app/tv-shows/1396/season/5/)
=> style: update tv season detail page styles

app/components/elements/shared/AuthForm.tsx, app/components/layouts/Layout.tsx, app/components/layouts/MultiLevelDropdown.tsx, app/hooks/useToast.ts, app/root.tsx, app/routes/_auth+/sign-in.tsx, app/routes/_auth+/sign-out.tsx, app/routes/_auth+/sign-up.tsx, app/routes/admin.cache.tsx, app/routes/anime+/random.tsx, app/routes/design-system+/button.tsx, app/routes/test.tsx, app/routes/trending+/$mediaType.tsx, app/utils/misc.ts, app/utils/server/toast-session.server.ts, pnpm-lock.yaml
@ctuanle 
- add toast flash messages
- add [toast session server utils](https://github.com/Khanhtran47/Sora/blob/cfd385380655e2cdf4ceb9bd04b3237408b5bccb/app/utils/server/toast-session.server.ts)
- add toast messages for sign in, sign up, redirect
=> feat: add toast flash messages
